version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_HOST_AUTH_METHOD: trust
      #POSTGRES_DB: core_development
      POSTGRES_DB: core_development
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
